# Makefile pour compiler tous les fichiers *.c

CC = g++

# Cible pour compiler et exécuter le programme
all: $(TARGET)

# Dépendances
$(TARGET): $(OBJS)
	$(CC) -o $(TARGET) $(OBJS)

# Règles pour compiler les fichiers sources
%.o: %.c
	$(CC) -c -Wall $< -o $@

# Dépendances automatiques pour les fichiers sources
$(OBJS): $(SRCS:.cpp=.o)

# Définir les fichiers sources
SRCS = main.cpp

# Cible pour nettoyer les fichiers intermédiaires
clean:
	rm -f *.o $(TARGET)
